classe_index:
    path:     /
    defaults: { _controller: "classeBundle:Classe:index" }
    methods:  GET

classe_show:
    path:     /{id}/show
    defaults: { _controller: "classeBundle:Classe:show" }
    methods:  GET

classe_new:
    path:     /new
    defaults: { _controller: "classeBundle:Classe:new" }
    methods:  [GET, POST]

classe_edit:
    path:     /{id}/edit
    defaults: { _controller: "classeBundle:Classe:edit" }
    methods:  [GET, POST]

classe_delete:
    path:     /{id}/delete
    defaults: { _controller: "classeBundle:Classe:delete" }
    methods:  DELETE


classe_ajouterClasse:
    path:     /ajouterClasse
    defaults: { _controller: classeBundle:Classe:ajouterClasse }
classe_afficherClasse:
    path:     /afficherClasse
    defaults: { _controller: classeBundle:Classe:index2 }
classe_supprimerClasse:
    path:     /supprimerClasse/{id}
    defaults: { _controller: classeBundle:Classe:supprimerClasse }
classe_modifierClasse:
    path:     /modifierClasse/{id}
    defaults: { _controller: classeBundle:Classe:modifierClasse }
classe_voirClasse:
    path:     /voirClasse/{id}
    defaults: { _controller: classeBundle:Classe:voirClasse }