admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Admin

enfants:
    resource: "@EnfantsBundle/Resources/config/routing.yml"
    prefix:   /enfants

classe:
    resource: "@classeBundle/Resources/config/routing.yml"
    prefix:   /classe

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
